### ISSUE TITLE
GK7CQ8S PROBLEM

### ISSUE THREAD

**Issue by cengizzzb** [kirainmoe/tongfang-utility#38]
hello kirainmoe, I need your help about your EFI folders.

I have a Monster(turkey reseller) which is have barebone GK7CQ8S and have these equipments

Model Name | Monster Tulpar T7 V19.6
Motherboard | Intel Cannon Point HM370
CPU | Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (max. 4.50GHz) Coffee Lake-H
RAM | Samsung 16 GB(8+8) 2666 MHz DDR4 SDRAM
Graphic Card | Intel(R) UHD Graphics 630 (1 GB)
Wi-Fi | Intel(R) Wireless-AC 9560 802.11n
Sound card | Realtek ALC269
BIOS Versiyonu | N.1.01

I installed Catalina first and I successfully passed setup screen I reached Mac main screen even I installed some specific applications from App Store so I used easily and stable than I restarted and I have a problem. 

This is a freezing and locking problem and it takes between 30 seconds and 1 minute after the computer is turned on. (mouse does not move keyboard is not responding.)

But what is strange is that when I restart it 3 times, I can use it stably and now I write from MAC because I don't have a windows setup.

I really do not understand what is the difference between these hardware because the only difference is the same as the hardware of our SUTSURUP friend, the only difference is the bios version.

here I attached the EFI files I used

![Ekran Resmi 2021-01-27 19 09 44](https://user-images.githubusercontent.com/78096771/106020597-039f3c80-60d5-11eb-84b5-7d877e15dc13.png)
![Ekran Resmi 2021-01-27 19 10 09](https://user-images.githubusercontent.com/78096771/106020611-06019680-60d5-11eb-8d83-767e3f684936.png)

**Comment by kirainmoe** [comment]
Can you provide the model of SSD that you are using?

**Comment by cengizzzb** [comment]
ADATA SU630

**Comment by kirainmoe** [comment]
Do you have any other NVMe SSD? I suspect the problem may be caused by the incompatible NVMe SSD.  I don't have other idea, you can try a fresh install.

**Comment by cengizzzb** [comment]
I have a samsung ssd

**Comment by kirainmoe** [comment]
If you have a Samsung PM981 / PM991 / PM981a, that will be the cause of freeze screen.

**Comment by cengizzzb** [comment]
Samsung PM981 yes i have this one, now I enabled NVMe SSDT, do you think is it enough?

**Comment by kirainmoe** [comment]
You need to ensure that Samsung PM981 is plugged in the first m.2 NVMe slot (which is close to the CPU fan) to make the DNVME SSDT takes effect.

**Comment by cengizzzb** [comment]
but I have a guarantee if I do this it is gonna be off guarantee but I think it is stable now idk maybe it is gonna be repeat
![Ekran Resmi 2021-01-28 06 43 33](https://user-images.githubusercontent.com/78096771/106087036-3cbac980-6134-11eb-9e65-ecf9c02ec97a.png)

**Comment by cengizzzb** [comment]
![Ekran Resmi 2021-01-28 06 46 09](https://user-images.githubusercontent.com/78096771/106087183-82779200-6134-11eb-9974-018c4e013b37.png)

**Comment by cengizzzb** [comment]
![Ekran Resmi 2021-01-28 06 47 29](https://user-images.githubusercontent.com/78096771/106087262-b2269a00-6134-11eb-9607-3065c376f7f4.png)

but im seeing in desktop this drive, I installed windows, is it an issue?

**Comment by kirainmoe** [comment]
dnvme just disabled pm981, other ssd will be present.

**Comment by cengizzzb** [comment]
I understood you say it is ok now, so what should i do if it happens again?
