### ISSUE TITLE
macOS环境下如果桌面存在Tongfang_EFI文件夹，更新efi并不会成功

### ISSUE THREAD

**Issue by youzhiran** [kirainmoe/tongfang-utility#40]

**Comment by kirainmoe** [comment]
不知道你指的更新时下载 EFI 还是替换到硬盘，我自己在桌面先创建了文件夹然后再下载，并没有什么问题。如果你指的是前者，请检查 Tongfang_EFI 文件夹的权限。

如果你指的是后者，如果在替换前 EFI 分区已经被手动挂载，则可能出现因为重复挂载而没有替换上的情况，这似乎是 macOS diskutil 命令的问题。
