### ISSUE TITLE
机械革命X3在v3.1.5中配置文件版本21.3.6中下载的efi，开机后提示电脑因出现问题而重新启动，请按下按键，或等待几秒以继续启动然后就重启选择Windows还是mac 再进mac还是一样的 说明这个efi并不适用所有人，请把上个版本的efi文件发出来把 

### ISSUE THREAD

**Issue by wgrun** [kirainmoe/tongfang-utility#44]
机械革命X3在v3.1.5中配置文件版本21.3.6中下载的efi，开机后提示电脑因出现问题而重新启动，请按下按键，或等待几秒以继续启动然后就重启选择Windows还是mac 再进mac还是一样的 说明这个efi并不适用所有人，请把上个版本的efi文件发出来把

**Comment by kirainmoe** [comment]
请提供 -v 模式跑码截图。
